### ISSUE TITLE
Burned my OLED

### ISSUE THREAD

**Issue by Naesstrom** [stefschin/BrewPiLess-32-PCB#3]
I finally got around to hook up my board on the test bench but the first thing that happened was that I burnt my OLED.
Apparently there are 2 versions of 4-pin OLEDS, I had this pinout:
![image](https://user-images.githubusercontent.com/6575206/131389222-51f5127f-b5e6-40bd-b336-b3d1138094c1.png)
vcc-gnd-scl-sda

Checking on some 7 pin ones I noticed they had vcc and gnd switched and so does some other 4-pin versions to.
So just a heads up, might need to mention that it should be a 4-pin with the correct order 😅
![image](https://user-images.githubusercontent.com/6575206/131390448-c596db40-9358-450d-bc29-d54519d48f65.png)
**gnd-vcc-scl-sda**

**Comment by stefschin** [comment]
Sorry for that Erik!!! I have 7 pins oled and I make it compatible to 4 pin oled because I'ts most used. I was based on this information: 
![Captura 1](https://user-images.githubusercontent.com/32103938/131390248-fd1c0955-27d4-4cdc-ab15-741c29eda17b.JPG)
![Captura 2](https://user-images.githubusercontent.com/32103938/131390256-2640fd37-ef0f-4656-853e-1d90917105be.JPG)

I will put a Warning to this! Connection is for GND-VCC-SCL-SDA models
And I will make a new version of PCB with a jumper to set GND-VCC or VCC-GND model.

**Comment by Naesstrom** [comment]
Yeah I saw when I ordered my new Oled last night that the shop had a warning to that the pinout might be different! No worries just wanted to help in anyway I can!

Great work on the PCB, done a few myself so I know what a pain it can be to get a really good layout 😄 
![image](https://user-images.githubusercontent.com/6575206/131458129-db81b2c2-9de6-421b-a6d9-ef0161e7734e.png)

Still havn't decided if I will use a ADS1115 or the built in, probably try both since I have the parts for it!

**Comment by stefschin** [comment]
Thanks @Naesstrom !! I'm Electronic Engineer specialised in PCB design, multi-layer, for aerospace, etc, so this board wasn't difficult to make but I like to design for different users so I think more in the flexibility of the design, like is Arduino, etc but with better reliability. Hope is it working without issues. I add a Warning about Oled so I close the issue. Good luck with ADC Input. Cheers
