### ISSUE TITLE
Devkitc V4 power from 5v pin hangs on boot

### ISSUE THREAD

**Issue by frank-nobrega** [stefschin/BrewPiLess-32-PCB#6]
I haven't built this board but I have tried to run BrewPiLess on a Devkitc V4 board and it runs fine if I power it from the built in USB port but if I power from the 5V pin, it doesn't like it.  I sometimes get it to run long enough to bring up BrewPiLess but it crashes within 30 seconds.  Other times it won't connect at all.  Any ideas on a source for boards can be powered through the 5V pin?

**Comment by stefschin** [comment]
It depends on your 5V source, maybe it's not a good power supply and stays without enough current for Wifi, which is the most demanding momento for PS. When you power it with USB it has a diode to protect USB if you connect two powers together, so USB voltage drops to aprox 4.5V and still works ok because you have a regulator to 3.3V which is the voltage that uses ESP32 internally, but when a Power Supply has power demanding and it can't deliver it, his voltage drops and when voltage drops from 3V normally crashes o has mal functions. You have to choose a power supply that deliveries 5V with at least 200-250 mA, USB has 500 mA, so you can try with a cellphone charger that has more than 500 mA... hop it helps

**Comment by stefschin** [comment]
No news, I think problem is solved.

**Comment by frank-nobrega** [comment]
Using the same power supply it runs fine if I power through the USB port but hangs if I power via 5V pin.  Must be something with my DevKitC V4 board.  The power supply I am using is rated for 3A.  Is there a particular brand of board you are using?

**Comment by stefschin** [comment]
No, here in Argentina we get boards mainly from China. An there are many models, that's why I let 3 boards option. Maybe you can try just your board with USB port, to see if it's something DevKitC V4 board or BPL-32 PCB. If something is consuming more than 500 mA it hangs USB port but not the PS.

**Comment by frank-nobrega** [comment]
Works fine if powered by USB directly.

**Comment by stefschin** [comment]
Did you have Digital Multimeter? Generally they have a DC current measurement so you can measure how much current it's draining from PS to the PCB. I think normally is less than 100 mA, but you can make the measurement to see if it's anything wrong with your board. As other users don't have same problem I assume that's something in your set up, you have to check current with or without modules, check for solder in places that doesn't go, component values, etc
